lesson2
Relaxiy/courses pull request #1
Opened 2021-11-06 14:49 UTC by Relaxiy

2021-11-09 19:57 UTC, damalikov commented on src/lesson2/Task11.java
> +        System.out.println("H" + T / 3600 + "ч M" + T / 60 + "мин S" + T + "с");
Задача состоит в том, чтобы указать сколько в этом количестве секунд часов, минут, секунд. 
например 125 секунд должно вывести 0ч. 2м. 5с.

2021-11-09 20:01 UTC, damalikov requested changes

2021-11-09 20:01 UTC, damalikov commented on src/lesson2/Task14.java
> +                break;
Как я упоминал на последнем занятии break использовать запрещено за исключеним, когда мы его используем в switch.

2021-11-09 20:01 UTC, damalikov commented on src/lesson2/Task14.java
> +        while(true) {
Не очень хорошее условие для цикла. Можно получить бесконечный цикл по итогу. Вообще в этой задче циклы в принципе не подрозумивались

2021-11-09 20:01 UTC, damalikov commented on src/lesson2/Task15.java
> +        double rez = (b + Math.sqrt(Math.pow(b, 2) + 4 * a * c)) / (2 * a) - a * 3 * c + Math.pow(b, -3);
можо вернуть это выражение без объявления переменной

2021-11-09 20:01 UTC, damalikov commented on src/lesson2/Task15.java
> +        while(true) {
Смотри комментарии к Task14

2021-11-10 10:51 UTC, Relaxiy commented on src/lesson2/Task15.java
> +        while(true) {
Исправил все задания в двух ветках

2021-11-14 19:30 UTC, damalikov approved these changes

2021-11-14 19:31 UTC, merged